name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install YARA deps
      run: sudo apt-get install -y automake libtool make gcc pkg-config libssl-dev libjansson-dev libmagic-dev
    - name: Build YARA
      working-directory: ./yari-sys/yara
      run: |
        ./bootstrap.sh
        CFLAGS="-fPIC" ./configure --enable-debug --disable-shared --enable-static --enable-cuckoo --enable-magic --enable-dotnet --with-crypto
        make
    - name: Build
      run: cargo build
    - name: Run Rust tests
      run: |
        RUST_LOG=debug cargo test
    - name: Run tests with yari using bundled bindings
      run: |
        cargo clean
        YARI_USE_BUNDLED_BINDINGS=1 RUST_LOG=debug cargo test
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run Python tests
      working-directory: ./yari-py
      run: |
        pip install --upgrade pip
        python -m venv env
        . env/bin/activate
        pip install maturin pytest
        maturin develop
        pytest tests
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install YARA deps
      run: brew install autoconf automake libtool pkg-config jansson libmagic openssl python@3.10 python@3.11 python@3.12
    - name: Build Yara
      working-directory: ./yari-sys/yara
      run: |
        ./bootstrap.sh
        CFLAGS="-fPIC -I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib $LDFLAGS" LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH" ./configure --enable-debug --disable-shared --enable-static --enable-cuckoo --enable-magic --enable-dotnet --with-crypto
        make
    - name: Build Yari (yari-sys)
      working-directory: ./yari-sys
      run: |
        CFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib $LDFLAGS" LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH" cargo build
    - name: Build Yari (yari-cli)
      working-directory: ./yari-cli
      run: |
        CFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib $LDFLAGS" LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH" cargo build
    - name: Run Rust tests
      run: |
        CFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib $LDFLAGS" LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH" RUST_LOG=debug cargo test
    - name: Run Rust tests with bundled bindings
      run: |
        cargo clean
        YARI_USE_BUNDLED_BINDINGS=1 CFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib $LDFLAGS" LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH" RUST_LOG=debug cargo test
    - name: Run Python tests
      working-directory: ./yari-py
      run: |
        python3.12 -m venv .venv 
        .venv/bin/pip install maturin pytest 
        CFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib $LDFLAGS" LIBRARY_PATH="$(brew --prefix)/lib:$LIBRARY_PATH" .venv/bin/maturin build -i python3.10 -i python3.11 -i python3.12
        .venv/bin/maturin build 
        .venv/bin/maturin develop 
        .venv/bin/pytest
