name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install YARA deps
      run: sudo apt-get install -y automake libtool make gcc pkg-config libssl-dev libjansson-dev libmagic-dev
    - name: Build YARA
      run: cd yari-sys/yara && ./bootstrap.sh && CFLAGS="-fPIC" ./configure --enable-debug --disable-shared --enable-static --enable-cuckoo --enable-magic --enable-dotnet --with-crypto && make
    - name: Build
      run: cargo build --verbose
    - name: Run Rust tests
      run: cargo test --verbose
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install yari-py deps
      run: pip install maturin pytest
    - name: Build Python package
      run: maturin develop
    - name: Run Python tests
      run: pytest tests
